// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stage1st.proto

/*
Package stage1stpb is a generated protocol buffer package.

It is generated from these files:
	stage1st.proto

It has these top-level messages:
	Post
	ThreadInfo
	Thread
*/
package stage1stpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Post struct {
	Content  string `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
	Author   string `protobuf:"bytes,2,opt,name=author" json:"author,omitempty"`
	PostTime int64  `protobuf:"varint,3,opt,name=post_time,json=postTime" json:"post_time,omitempty"`
}

func (m *Post) Reset()                    { *m = Post{} }
func (m *Post) String() string            { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()               {}
func (*Post) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Post) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Post) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Post) GetPostTime() int64 {
	if m != nil {
		return m.PostTime
	}
	return 0
}

type ThreadInfo struct {
	Rank      int32 `protobuf:"varint,1,opt,name=rank" json:"rank,omitempty"`
	Replies   int32 `protobuf:"varint,2,opt,name=replies" json:"replies,omitempty"`
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *ThreadInfo) Reset()                    { *m = ThreadInfo{} }
func (m *ThreadInfo) String() string            { return proto.CompactTextString(m) }
func (*ThreadInfo) ProtoMessage()               {}
func (*ThreadInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ThreadInfo) GetRank() int32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func (m *ThreadInfo) GetReplies() int32 {
	if m != nil {
		return m.Replies
	}
	return 0
}

func (m *ThreadInfo) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Thread struct {
	ThreadId    int32         `protobuf:"varint,1,opt,name=thread_id,json=threadId" json:"thread_id,omitempty"`
	ForumId     int32         `protobuf:"varint,2,opt,name=forum_id,json=forumId" json:"forum_id,omitempty"`
	Title       string        `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	ThreadInfos []*ThreadInfo `protobuf:"bytes,4,rep,name=thread_infos,json=threadInfos" json:"thread_infos,omitempty"`
	Posts       []*Post       `protobuf:"bytes,5,rep,name=posts" json:"posts,omitempty"`
}

func (m *Thread) Reset()                    { *m = Thread{} }
func (m *Thread) String() string            { return proto.CompactTextString(m) }
func (*Thread) ProtoMessage()               {}
func (*Thread) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Thread) GetThreadId() int32 {
	if m != nil {
		return m.ThreadId
	}
	return 0
}

func (m *Thread) GetForumId() int32 {
	if m != nil {
		return m.ForumId
	}
	return 0
}

func (m *Thread) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Thread) GetThreadInfos() []*ThreadInfo {
	if m != nil {
		return m.ThreadInfos
	}
	return nil
}

func (m *Thread) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

func init() {
	proto.RegisterType((*Post)(nil), "stage1stpb.Post")
	proto.RegisterType((*ThreadInfo)(nil), "stage1stpb.ThreadInfo")
	proto.RegisterType((*Thread)(nil), "stage1stpb.Thread")
}

func init() { proto.RegisterFile("stage1st.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x90, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x89, 0xc9, 0xc6, 0x64, 0x2a, 0x22, 0x83, 0x94, 0x15, 0x3d, 0x94, 0x1c, 0xa4, 0xa7,
	0x80, 0x7a, 0xf2, 0x11, 0x7a, 0x93, 0xa5, 0x82, 0xb7, 0x92, 0x9a, 0xad, 0x0d, 0x36, 0xd9, 0x65,
	0x77, 0xfa, 0x70, 0xbe, 0x9d, 0xfb, 0x27, 0x31, 0xde, 0xe6, 0x9b, 0x8f, 0xf9, 0xcd, 0x37, 0x03,
	0xd7, 0x96, 0x9a, 0x2f, 0xf9, 0x64, 0xa9, 0xd6, 0x46, 0x91, 0x42, 0x98, 0xb4, 0xde, 0x57, 0xef,
	0x90, 0xbd, 0x29, 0x4b, 0xc8, 0xe1, 0xf2, 0x53, 0x0d, 0x24, 0x07, 0xe2, 0xc9, 0x2a, 0x59, 0x97,
	0x62, 0x92, 0xb8, 0x84, 0xbc, 0x39, 0xd3, 0x51, 0x19, 0x7e, 0x11, 0x8c, 0x51, 0xe1, 0x3d, 0x94,
	0xda, 0x4d, 0xee, 0xa8, 0xeb, 0x25, 0x4f, 0x9d, 0x95, 0x8a, 0xc2, 0x37, 0xb6, 0x4e, 0x57, 0x1f,
	0x00, 0xdb, 0xa3, 0x91, 0x4d, 0xbb, 0x19, 0x0e, 0x0a, 0x11, 0x32, 0xd3, 0x0c, 0xdf, 0x81, 0xcc,
	0x44, 0xa8, 0xfd, 0x42, 0x23, 0xf5, 0xa9, 0x93, 0x36, 0x70, 0x99, 0x98, 0x24, 0x3e, 0x40, 0xe9,
	0x99, 0x2e, 0x64, 0xaf, 0x47, 0xf0, 0xdc, 0xa8, 0x7e, 0x12, 0xc8, 0x23, 0xda, 0x27, 0xa0, 0x50,
	0xed, 0xba, 0x76, 0x64, 0x17, 0xb1, 0xb1, 0x69, 0xf1, 0x0e, 0x8a, 0x83, 0x32, 0xe7, 0xde, 0x7b,
	0xe3, 0x82, 0xa0, 0x9d, 0x75, 0x0b, 0x8c, 0x3a, 0x3a, 0xc5, 0xd4, 0xa5, 0x88, 0x02, 0x5f, 0xe1,
	0x6a, 0xa2, 0xb9, 0xcc, 0x96, 0x67, 0xab, 0x74, 0xbd, 0x78, 0x5e, 0xd6, 0xf3, 0xb3, 0xea, 0xf9,
	0x24, 0xb1, 0xa0, 0xbf, 0xda, 0xe2, 0x23, 0x30, 0x7f, 0xb9, 0xe5, 0x2c, 0xcc, 0xdc, 0xfc, 0x9f,
	0xf1, 0xdf, 0x15, 0xd1, 0xde, 0xe7, 0xe1, 0xff, 0x2f, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe4,
	0x30, 0x87, 0x02, 0x91, 0x01, 0x00, 0x00,
}
