// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stage1st.proto

/*
Package stage1stpb is a generated protocol buffer package.

It is generated from these files:
	stage1st.proto

It has these top-level messages:
	Post
	ThreadInfo
	Thread
*/
package stage1stpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Post struct {
	Content      string `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
	Author       string `protobuf:"bytes,2,opt,name=author" json:"author,omitempty"`
	PostTimeMsec int32  `protobuf:"varint,3,opt,name=post_time_msec,json=postTimeMsec" json:"post_time_msec,omitempty"`
}

func (m *Post) Reset()                    { *m = Post{} }
func (m *Post) String() string            { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()               {}
func (*Post) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Post) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Post) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Post) GetPostTimeMsec() int32 {
	if m != nil {
		return m.PostTimeMsec
	}
	return 0
}

type ThreadInfo struct {
	Rank    int32 `protobuf:"varint,1,opt,name=rank" json:"rank,omitempty"`
	Replies int32 `protobuf:"varint,2,opt,name=replies" json:"replies,omitempty"`
}

func (m *ThreadInfo) Reset()                    { *m = ThreadInfo{} }
func (m *ThreadInfo) String() string            { return proto.CompactTextString(m) }
func (*ThreadInfo) ProtoMessage()               {}
func (*ThreadInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ThreadInfo) GetRank() int32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func (m *ThreadInfo) GetReplies() int32 {
	if m != nil {
		return m.Replies
	}
	return 0
}

type Thread struct {
	ThreadId    int32         `protobuf:"varint,1,opt,name=thread_id,json=threadId" json:"thread_id,omitempty"`
	ForumId     int32         `protobuf:"varint,2,opt,name=forum_id,json=forumId" json:"forum_id,omitempty"`
	ThreadInfos []*ThreadInfo `protobuf:"bytes,3,rep,name=thread_infos,json=threadInfos" json:"thread_infos,omitempty"`
	Posts       []*Post       `protobuf:"bytes,4,rep,name=posts" json:"posts,omitempty"`
}

func (m *Thread) Reset()                    { *m = Thread{} }
func (m *Thread) String() string            { return proto.CompactTextString(m) }
func (*Thread) ProtoMessage()               {}
func (*Thread) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Thread) GetThreadId() int32 {
	if m != nil {
		return m.ThreadId
	}
	return 0
}

func (m *Thread) GetForumId() int32 {
	if m != nil {
		return m.ForumId
	}
	return 0
}

func (m *Thread) GetThreadInfos() []*ThreadInfo {
	if m != nil {
		return m.ThreadInfos
	}
	return nil
}

func (m *Thread) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

func init() {
	proto.RegisterType((*Post)(nil), "stage1stpb.Post")
	proto.RegisterType((*ThreadInfo)(nil), "stage1stpb.ThreadInfo")
	proto.RegisterType((*Thread)(nil), "stage1stpb.Thread")
}

func init() { proto.RegisterFile("stage1st.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x89, 0x4d, 0x62, 0x3b, 0x2d, 0x45, 0xe6, 0x50, 0x56, 0xbc, 0x48, 0x10, 0xe9, 0x29,
	0xa0, 0x9e, 0xf4, 0x1f, 0xf4, 0x20, 0xc8, 0xd2, 0xb3, 0x21, 0x6d, 0xb6, 0x36, 0x68, 0xb2, 0x61,
	0x67, 0xfa, 0x8b, 0xfc, 0xa3, 0xee, 0x4e, 0x12, 0xdb, 0xdb, 0xbc, 0xf7, 0xf8, 0xf6, 0xcd, 0x0e,
	0x2c, 0x89, 0xcb, 0x2f, 0xf3, 0x44, 0x9c, 0x77, 0xce, 0xb2, 0x45, 0x18, 0x75, 0xb7, 0xcb, 0x3e,
	0x21, 0xfe, 0xb0, 0xc4, 0xa8, 0xe0, 0x7a, 0x6f, 0x5b, 0x36, 0x2d, 0xab, 0xe8, 0x3e, 0x5a, 0xcf,
	0xf4, 0x28, 0x71, 0x05, 0x69, 0x79, 0xe2, 0xa3, 0x75, 0xea, 0x4a, 0x82, 0x41, 0xe1, 0x03, 0x2c,
	0x3b, 0x4f, 0x16, 0x5c, 0x37, 0xa6, 0x68, 0xc8, 0xec, 0xd5, 0xc4, 0xe7, 0x89, 0x5e, 0x04, 0x77,
	0xeb, 0xcd, 0x77, 0xef, 0x65, 0x6f, 0x00, 0xdb, 0xa3, 0x33, 0x65, 0xb5, 0x69, 0x0f, 0x16, 0x11,
	0x62, 0x57, 0xb6, 0xdf, 0x52, 0x91, 0x68, 0x99, 0x43, 0xb3, 0x33, 0xdd, 0x4f, 0x6d, 0x48, 0x0a,
	0x12, 0x3d, 0xca, 0xec, 0x37, 0x82, 0xb4, 0x87, 0xf1, 0x0e, 0x66, 0x2c, 0x53, 0x51, 0x57, 0x03,
	0x3d, 0xed, 0x8d, 0x4d, 0x85, 0xb7, 0x30, 0x3d, 0x58, 0x77, 0x6a, 0x42, 0x36, 0x3c, 0x21, 0xda,
	0x47, 0xaf, 0xb0, 0x18, 0x39, 0xdf, 0x4f, 0x7e, 0xc5, 0xc9, 0x7a, 0xfe, 0xbc, 0xca, 0xcf, 0x17,
	0xc8, 0xcf, 0xeb, 0xe9, 0x39, 0xff, 0xcf, 0x84, 0x8f, 0x90, 0x84, 0x9f, 0x90, 0x8a, 0x85, 0xb9,
	0xb9, 0x64, 0xc2, 0xc9, 0x74, 0x1f, 0xef, 0x52, 0x39, 0xea, 0xcb, 0x5f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x7d, 0x23, 0x7c, 0xf2, 0x66, 0x01, 0x00, 0x00,
}
